template_type: TF 
template_version: 0.12

template_parameters:
  variables:
   access : system
  variable_files:
   - ./tf11/tf11_tests-2.jx
   - ./tfplan/terraform12module/smelks.tfvars

tags:
- Org:Engineering
- Team:Shift_LeftQAsprint25
- env25:Y
- teamb:ball
- teamb1:ball1
- teamb2:ball2
- teamb3:ball3
- teamb3:ball4
- teamb4:ball5
- teamd:donut
- teamd6:مرحبا
- teamd7:a$b
- env31:arn:aws:iam::349006084872
- env32:ShiftLeft

