template_type: TF 
template_version: 0.12

template_parameters:
variables:
 key1: 1
 key2: 2

variable_files:
 - ./filepath/filename1
 - ./filepath/filename2

tags:
- Org:Engineering
- Team:Shift_LeftQAsprint25
- env25:Y
