template_type: k8s 
template_version: 0.12


tags:
- Org:Engineering
- Team:Shift_LeftQAsprint25
- env25:Y
- teamb:ball
- teamb1:ball1
- teamb2:ball2
- teamb3:ball3
- teamb3:ball4
- teamb4:ball5
- teamd:donut
- teamd6:مرحبا
- teamd7:a$b
